### ISSUE TITLE
Security Vulnerability with `semver` (via `cross-spawn` Transitive Dependency)

### ISSUE THREAD

**Issue by brianlenz** [medikoo/child-process-ext#2]
`cross-spawn` `6.0.5` depends on `semver` `^5.5.0` which has a vulnerability:

https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

The solution is to upgrade `cross-spawn` to `^7.0.3` which no longer depends on `semver`.

**Comment by medikoo** [comment]
@brianlenz thanks for reporting. Released with v3.0.0
